### ISSUE TITLE
2 Problems

### ISSUE THREAD

**Issue by fineartist99** [edse/puzzle#1]
Hey there, I was playing around with your puzzle program here and for one, I think it's really great.  But I did come across 2 errors.
1. sometimes when I'd play the puzzle game and complete one puzzle and click next stage the same exact puzzle/image would be used but just broken up.  Sometime it would work how it's supposed to, were different images would get used.  Randomly - just like it's supposed to.
2. on the third stage every time I get a bunch of 3's for the timer.  looks like there should be some numbers in front of the decimal but it end's up looking like .333333333  I attached a screen grab

I'll try to see why this is happening but if you or anyone else figures this out let me know.
![screen shot 2013-10-09 at 10 04 33 pm](https://f.cloud.github.com/assets/5652114/1303333/4721d3f2-3151-11e3-9e9c-4faa9c28705f.png)

**Comment by edse** [comment]
Hey @fineartist99, thank you very much for your interest and feedback.

Both problems are now fixed.

Have fun!
