### ISSUE TITLE
Google Chrome images away from the mouse

### ISSUE THREAD

**Issue by artpromotion** [edse/puzzle#2]
Hello, this awesome puzzle has a nasty issue on google chrome, after stage II, when I drag an image, the image is away and not attached to the mouse, while it works on IE 9 and Firefox

Also on IE9, when placed inside an iframe, and clicking start game does not move:

While: $('html, body').animate({ scrollTop: 0 }, 'fast'); works outise n iframe, when placing the application inside an iframe, clicking start does not start

**Comment by edse** [comment]
Hi @artpromotion, thank you very much for your feedback.

The puzzle is now updated please check at: http://html5puzzle.appspot.com and http://html5puzzle.appspot.com/iframe.html

Let me know if you have any trouble.

Best regards,

Emerson Estrella
